### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [CarlosVitr/Lemon_theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by CarlosVitr** [comment]
At the moment it is in beta, and I am adding some colors so it is without the capture screen, as soon as I fix it I will add it, thanks for the Feedback.

**Comment by unixorn** [comment]
Ok. Close this issue when you're done and I will add it to the list, or you can PR it in yourself, whatever is more convenient for you.

**Comment by CarlosVitr** [comment]
Ok
